# Generated by Django 4.2.5 on 2023-10-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                ("client_phone", models.IntegerField()),
                ("client_address", models.CharField(max_length=200)),
                ("client_create_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_name", models.CharField(max_length=100)),
                ("goods_description", models.CharField(max_length=200)),
                ("goods_price", models.IntegerField()),
                ("goods_amount", models.IntegerField()),
                ("goods_create_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_price", models.IntegerField()),
                ("order_create_at", models.DateField(auto_now_add=True)),
                (
                    "order_client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp2.client"
                    ),
                ),
                (
                    "order_goods_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp2.goods"
                    ),
                ),
            ],
        ),
    ]
