# Generated by Django 4.2.5 on 2023-10-04 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="order_price",
        ),
    ]
